### ISSUE TITLE
Social icons show as black in the dark theme

### ISSUE THREAD

**Issue by macbutch** [526avijitgupta/gokarna#78] opened 2021-12-14 21:54 UTC
I had a look at the CSS and can't see any obvious reason for this. The icons are dark on the light theme (which is correct) but for the dark theme they show as black (hard to see) until you mouse over/hover on them and they change.

Happy to help with testing but CSS is not a strong point for me (otherwise I'd submit a fix)!

I've worked around this by adding my icons to the menu instead and I'm pretty happy with that option for now.

**Comment by yashmehrotra** [comment] 2021-12-15 05:43
@macbutch Thank you for reporting it

Can you please send us:
1. Link to the codebase you're seeing this problem in
2. A screenshot in both light and dark theme

This would help us narrow down the issue

**Comment by harlanhutton** [comment] 2022-01-12 21:02
Hi @macbutch! I'm having the same issue. Did you figure out a solution other than using your own icons? One of my icons works perfectly when I toggle but the LinkedIn one remains black on light and dark modes 

<img width="218" alt="Screen Shot 2022-01-12 at 2 01 26 PM" src="https://user-images.githubusercontent.com/52501816/149220904-0757f7e7-a65c-43b7-8a73-3f0e4adf9257.png">

**Comment by macbutch** [comment] 2022-01-13 02:38
@harlanhutton no, sorry, I ended up just not using the social icons because I couldn't get them to look right.

**Comment by yashmehrotra** [comment] 2022-01-18 11:19
@harlanhutton I tried recreating the issue but was unable to, is it possible to get a live preview or link to the source code

**Comment by camdecoster** [comment] 2022-02-22 23:53
It seems to be related to the link visited state. I can see it on the [demo site](https://gokarna-hugo.netlify.app/). Just click one of the social links, then try the demo again.

**Comment by 526avijitgupta** [comment] 2022-02-24 11:13
@camdecoster Good catch! Could you please create a PR in this repo for the fix? It'll autodeploy and generate a preview link where it can be quickly tested and merged :)

**Comment by camdecoster** [comment] 2022-02-26 22:12
I just submitted one.

**Comment by yashmehrotra** [comment] 2022-02-27 13:33
Thanks @camdecoster #81 is merged now

**Closed** 2022-02-27 13:32 UTC

**Comment by realansgar** [comment] 2022-07-27 02:23
Unfortunately, this fix broke the hover effect for social icons. See #104

**Comment by camdecoster** [comment] 2022-07-27 16:14
It seems to be working for me. Do you have an example of where it isn't working or can you provide steps to reproduce?

**Comment by camdecoster** [comment] 2022-07-27 19:40
Never mind, I see it now. Good catch. I'll follow your issue for updates.
